<?php
/**
 * Mattermost Perforce Swarm module
 *
 * @copyright   2026 PoFig Games Studio. All rights reserved.
 * @license     Please see LICENSE.txt in top-level readme folder of this distribution.
 */
namespace Mattermost\Service;

use Activity\Model\Activity;
use Activity\Model\IActivity;
use Application\Config\ConfigManager;
use Application\Config\IConfigDefinition as IDef;
use Application\Config\IDao;
use Application\Connection\ConnectionFactory;
use Application\Factory\InvokableService;
use Application\Log\SwarmLogger;
use Exception;
use Groups\Model\Group;
use Interop\Container\ContainerInterface;
use InvalidArgumentException;
use Mail\MailAction;
use Mattermost\Config\IConfig;
use P4\Spec\Change;
use Projects\Model\Project;
use Reviews\Model\IReview;
use Reviews\Model\Review;
use Users\Model\IUser;

/**
 * Utility functions to be used by the Mattermost service.
 * @package Mattermost\Service
 */
class Utility implements IUtility, InvokableService
{
    const LOG_PREFIX = Utility::class;

    private $services;
    private $config;
    private $api;

    /**
     * @param ContainerInterface $services
     * @param array|null         $options
     */
    public function __construct(ContainerInterface $services, array $options = null)
    {
        $this->services = $services;
        $this->config   = $services->get(IDef::CONFIG);
        $this->api      = $services->get(IApi::SERVICE_NAME);
    }

    /**
     * @inheritDoc
     */
    public function getFileNames(Change $change, array $workspace = []): array
    {
        $limit     = (int) ($workspace[IConfig::SUMMARY_FILE_LIMIT] ?? 10);
        $fileNames = [];
        $files     = $change->getFileData($change->isPending());
        $count     = count($files);
        if ($count > $limit) {
            $files = array_slice($files, 0, $limit);
        }
        foreach ($files as $file) {
            $fileNames[] = $file['depotFile'] . '#' . $file['rev'];
        }
        return [self::FILES => $fileNames, self::COUNT => $count];
    }

    /**
     * @inheritDoc
     */
    public function getHostName(): string
    {
        $hostname    = ConfigManager::getValue($this->config, IDef::ENVIRONMENT_HOSTNAME);
        $externalURL = ConfigManager::getValue($this->config, IDef::ENVIRONMENT_EXTERNAL_URL);

        if ($externalURL !== null) {
            return $externalURL;
        }
        return "http://" . $hostname;
    }

    /**
     * @inheritDoc
     */
    public function buildActivityReply(
        Activity $activity,
        array $projects,
        array $linkedProjects = [],
        array $workspace = []
    ): string {
        $userDao = $this->services->get(IDao::USER_DAO);
        $p4      = $this->services->get(ConnectionFactory::P4_ADMIN);

        $userId = $activity->getRawValue(IActivity::USER);
        $action = $activity->getRawValue(IActivity::ACTION);
        $target = $activity->getRawValue(IActivity::TARGET);
        // If we are working with a description from a comment
        $rawDescription = $activity->getRawValue(IActivity::DESCRIPTION);
        $details        = $activity->getRawValue(IActivity::DETAILS);
        $description    = '';
        switch ($action) {
            case MailAction::COMMENT_ADDED:
            case MailAction::COMMENT_EDITED:
            case MailAction::COMMENT_REPLY:
            case MailAction::DESCRIPTION_COMMENT_ADDED:
            case MailAction::DESCRIPTION_COMMENT_EDITED:
                $description = $rawDescription;
                break;
            // Include transition comment in notifications
            case MailAction::REVIEW_NEEDS_REVIEW:
            case MailAction::REVIEW_NEEDS_REVISION:
            case MailAction::REVIEW_APPROVED:
            case MailAction::REVIEW_REJECTED:
            case MailAction::REVIEW_ARCHIVED:
                if (is_array($details) && isset($details['transitionComment'])) {
                    $description = $details['transitionComment'];
                }
                break;
        }

        // Fallback name for activity generated by system tasks that have no user record.
        $who = "Helix Swarm";
        if ($userDao->exists($userId, $p4)) {
            $who = $this->formatUser((string) $userId, $workspace);
        }

        $projects = count($projects) ? " for" . $this->buildProjectText($projects, false, $linkedProjects) : "";

        // Build vote context if vote counts are available in activity details.
        $voteContext = '';
        if (is_array($details) && isset($details['voteCounts'])) {
            $up          = (int) ($details['voteCounts']['up'] ?? 0);
            $down        = (int) ($details['voteCounts']['down'] ?? 0);
            $voteContext = sprintf(" (Votes: %d up, %d down)", $up, $down);
        }

        return sprintf(
            "%s %s %s%s%s%s",
            $who,
            $action,
            $target,
            $voteContext,
            $projects,
            $description !== '' ? ":\n" . $description : ""
        );
    }

    /**
     * @inheritDoc
     */
    public function getProjectMappings($projectList, $mappingList, $purePrivate = false): array
    {
        $result      = [];
        $mappingList = (array) $mappingList;

        foreach ($projectList as $project => $branches) {
            foreach ($mappingList as $type => $channels) {
                if ($project === $type) {
                    foreach ((array) $channels as $channel) {
                        $result[$channel] = array_merge($result[$channel] ?? [], [$project]);
                    }
                }
            }
        }

        // If purePrivate is true, then we shouldn't attempt to include the catch-all channels. If it is
        // false then we can assess if we want to send notifications to one of the three special mappings.
        if (!$purePrivate) {
            if (empty($result)) {
                // No project: use the *without_project* mappings; unmapped project: use *no_project_channel*
                $special = empty($projectList)
                    ? self::NO_ASSOCIATED_PROJECTS_CHANNELS
                    : self::DEFAULT_PROJECTS_CHANNELS;
                foreach ((array) ($mappingList[$special] ?? []) as $channel) {
                    $result[$channel] = array_merge($result[$channel] ?? [], [IUtility::NO_PROJECT_CHANNEL]);
                }
            }

            // Add '*all*' mappings for all reviews (regardless of above)
            foreach ((array) ($mappingList[self::ALL_NOTIFICATIONS_CHANNELS] ?? []) as $channel) {
                $result[$channel] = array_merge($result[$channel] ?? [], [IUtility::NO_PROJECT_CHANNEL]);
            }
        }

        return $result;
    }

    /**
     * @inheritDoc
     */
    public function buildProjectText(?array $projects, $markdown = true, array $linkedProjects = []): string
    {
        $projectDao    = $this->services->get(IDao::PROJECT_DAO);
        $p4            = $this->services->get(ConnectionFactory::P4_ADMIN);
        $lines         = [];
        $totalProjects = count((array) $projects);
        if ($projects && $totalProjects > 0) {
            foreach ($projects as $project => $branches) {
                $projectModel    = $projectDao->fetchById($project, $p4);
                $projectBranches = $projectModel->getBranches();
                $projectName     = $projectModel->getName();
                $isPrivate       = $projectModel->isPrivate();
                // If not private (or explicitly linked to this channel) create text.
                if (in_array($project, $linkedProjects) || !$isPrivate) {
                    foreach ($branches as $branch) {
                        try {
                            $branchData = $projectModel->getBranch($branch, $projectBranches);
                            $name       = $branchData[Project::FIELD_NAME];
                        } catch (InvalidArgumentException $e) {
                            $name = $branch;
                        }
                        $lines[] = $projectName . ":" . $name;
                    }
                }
            }
        }
        if (empty($lines)) {
            return '';
        }
        if ($markdown) {
            return "**Projects**:\n- " . implode("\n- ", $lines);
        }
        return " " . implode(", ", $lines);
    }

    /**
     * @inheritDoc
     */
    public function buildFileNames(Change $change, array $workspace = [], bool $force = false): string
    {
        $text             = '';
        $summaryFileNames = $workspace[IConfig::SUMMARY_FILE_NAMES] ?? false;

        if ($force || $summaryFileNames === true) {
            $fileData = $this->getFileNames($change, $workspace);
            $files    = $fileData[IUtility::FILES];
            $count    = $fileData[IUtility::COUNT];
            $text     = "**" . $count . " file" . ($count !== 1 ? "s have" : " has") . " been changed**";
            if ($count > 0) {
                $text .= ":";
                foreach ($files as $file) {
                    // Depot paths often contain '_' and '#', wrap in code spans so markdown leaves them alone
                    $text .= "\n- `" . str_replace('`', "'", $file) . "`";
                }
                // Total count of files was bigger than the list returned, add an indicator that there are more
                if ($count > count($files)) {
                    $text .= "\n- ...";
                }
            }
        }
        return $text;
    }

    /**
     * @inheritDoc
     */
    public function buildTitle(
        Change $change,
        Review $review = null,
        Activity $activity = null,
        array $workspace = []
    ): string {
        $author = $this->formatUser((string) $change->getUser(), $workspace);

        if ($review !== null) {
            return sprintf("%s requested review #%s", $author, $review->getId());
        }
        if ($activity && $activity->get('behalfOf')) {
            $committer = $this->formatUser((string) $activity->get('user'), $workspace);
            return sprintf("%s committed change #%s on behalf of %s", $committer, $change->getId(), $author);
        }
        return sprintf("%s committed change #%s", $author, $change->getId());
    }

    /**
     * @inheritDoc
     */
    public function formatUser(string $userId, array $workspace = []): string
    {
        $userDao  = $this->services->get(IDao::USER_DAO);
        $p4       = $this->services->get(ConnectionFactory::P4_ADMIN);
        $fullName = $userId;
        $handle   = $userId;
        try {
            $user     = $userDao->fetchById($userId, $p4);
            $fullName = (string) ($user->getRawValue(IUser::FIELD_FULLNAME) ?: $userId);
            $mmUser   = $this->resolveSwarmUser($userId, $workspace);
            if ($mmUser !== null && !empty($mmUser['username'])) {
                $handle = '@' . $mmUser['username'];
            }
        } catch (Exception $e) {
            $this->services->get(SwarmLogger::SERVICE)->debug(
                sprintf('%s: formatUser failed for "%s": %s', self::LOG_PREFIX, $userId, $e->getMessage())
            );
        }
        return sprintf('%s (%s)', $fullName, $handle);
    }

    /**
     * @inheritDoc
     */
    public function buildLink(Change $change, Review $review = null): string
    {
        $basePath = "/" . (P4_SERVER_ID ? P4_SERVER_ID . "/" : '');
        return $basePath . ($review ? "reviews/" . $review->getId() : "changes/" . $change->getId());
    }

    /**
     * @inheritDoc
     */
    public function buildDescription(Change $change): string
    {
        $description   = $change->getDescription();
        $defaultFormat = "**Description**:\n{description}";
        return strtr($defaultFormat, ['{description}' => $description]);
    }

    /**
     * @inheritDoc
     */
    public function resolveMattermostUser(string $email, array $workspace): ?array
    {
        return $this->api->findUserByEmail($email, $workspace);
    }

    /**
     * @inheritDoc
     */
    public function resolveSwarmUser(string $userId, array $workspace): ?array
    {
        if (empty($workspace[IConfig::TOKEN])) {
            return null;
        }
        $email = '';
        try {
            $user  = $this->services->get(IDao::USER_DAO)
                ->fetchById($userId, $this->services->get(ConnectionFactory::P4_ADMIN));
            $email = trim((string) $user->getRawValue(IUser::FIELD_EMAIL));
        } catch (Exception $e) {
            // unknown Swarm user: still try the id as a Mattermost username below
        }
        $mmUser = $email !== '' ? $this->resolveMattermostUser($email, $workspace) : null;
        if ($mmUser === null) {
            $mmUser = $this->api->findUserByUsername($userId, $workspace);
        }
        return $mmUser;
    }

    /**
     * @inheritDoc
     */
    public function buildMentions(
        array $notifyConfig,
        Change $change,
        ?array $projects,
        ?Review $review = null,
        array $workspace = []
    ): string {
        if (empty($notifyConfig)) {
            return '';
        }
        $logger     = $this->services->get(SwarmLogger::SERVICE);
        $validRoles = [
            IConfig::NOTIFY_AUTHOR,
            IConfig::NOTIFY_DEFAULT_REVIEWERS,
            IConfig::NOTIFY_BRANCH_MODERATORS,
            IConfig::NOTIFY_PROJECT_DEFAULT_REVIEWERS,
            IConfig::NOTIFY_PROJECT_OWNERS,
            IConfig::NOTIFY_PROJECT_MEMBERS,
            IConfig::NOTIFY_REVIEWERS,
        ];
        foreach ($notifyConfig as $role) {
            if (!in_array($role, $validRoles)) {
                $logger->warn(sprintf('%s: unrecognized notify value "%s"', self::LOG_PREFIX, $role));
            }
        }
        $p4      = $this->services->get(ConnectionFactory::P4_ADMIN);
        $userIds = [];
        if (in_array(IConfig::NOTIFY_AUTHOR, $notifyConfig)) {
            $userIds[] = ($review !== null) ? $review->get(IReview::FIELD_AUTHOR) : $change->getUser();
        }
        if ($review !== null && $projects !== null) {
            $projectDao      = $this->services->get(IDao::PROJECT_DAO);
            $wantRevs        = in_array(IConfig::NOTIFY_DEFAULT_REVIEWERS, $notifyConfig);
            $wantMods        = in_array(IConfig::NOTIFY_BRANCH_MODERATORS, $notifyConfig);
            $wantProjRevs    = in_array(IConfig::NOTIFY_PROJECT_DEFAULT_REVIEWERS, $notifyConfig);
            $wantProjOwners  = in_array(IConfig::NOTIFY_PROJECT_OWNERS, $notifyConfig);
            $wantProjMembers = in_array(IConfig::NOTIFY_PROJECT_MEMBERS, $notifyConfig);
            foreach ($projects as $projectId => $branches) {
                try {
                    $project     = $projectDao->fetchById($projectId, $p4);
                    $allBranches = $project->getBranches();
                } catch (Exception $e) {
                    continue;
                }
                foreach ($branches as $branchId) {
                    try {
                        $branchData = $project->getBranch($branchId, $allBranches);
                    } catch (InvalidArgumentException $e) {
                        continue;
                    }
                    if ($wantMods) {
                        foreach ($branchData[Project::FIELD_MODERATORS] ?? [] as $uid) {
                            $userIds[] = $uid;
                        }
                        foreach ($branchData[Project::FIELD_MODERATORS_GROUPS] ?? [] as $groupName) {
                            $userIds[] = 'swarm-group-' . $groupName;
                        }
                    }
                    if ($wantRevs) {
                        $defs = $branchData[Project::FIELD_DEFAULTS] ?? [];
                        foreach (array_keys($defs[Project::FIELD_REVIEWERS] ?? []) as $uid) {
                            $userIds[] = $uid;
                        }
                    }
                }
                if ($wantProjRevs) {
                    $projDefaults = $project->getDefaults();
                    foreach (array_keys($projDefaults[Project::FIELD_REVIEWERS] ?? []) as $uid) {
                        $userIds[] = $uid;
                    }
                }
                if ($wantProjOwners) {
                    foreach ($project->getOwners() as $uid) {
                        $userIds[] = $uid;
                    }
                }
                if ($wantProjMembers) {
                    $members = $project->getAllMembers(false, null) ?: [];
                    if (count($members) > 20) {
                        $logger->warn(
                            sprintf(
                                '%s: project_members for project "%s" has %d members (>20)',
                                self::LOG_PREFIX,
                                $projectId,
                                count($members)
                            )
                        );
                    }
                    foreach ($members as $uid) {
                        $userIds[] = $uid;
                    }
                }
            }
        }
        if ($review !== null && in_array(IConfig::NOTIFY_REVIEWERS, $notifyConfig)) {
            foreach ($review->getReviewers() as $uid) {
                $userIds[] = $uid;
            }
        }
        // Expand any group entries to their individual members (handles nested groups recursively).
        $groupDao        = $this->services->get(IDao::GROUP_DAO);
        $expandedUserIds = [];
        foreach (array_unique($userIds) as $uid) {
            if (Group::isGroupName($uid)) {
                try {
                    $members = $groupDao->fetchAllMembers(Group::getGroupName($uid), true, null, null, $p4);
                    foreach (array_keys($members) as $member) {
                        $expandedUserIds[] = $member;
                    }
                } catch (Exception $e) {
                    // skip group if it cannot be expanded
                }
            } else {
                $expandedUserIds[] = $uid;
            }
        }

        $mentions = [];
        foreach (array_unique($expandedUserIds) as $userId) {
            try {
                $mmUser = $this->resolveSwarmUser((string) $userId, $workspace);
                if ($mmUser) {
                    $mentions[$mmUser['id']] = '@' . $mmUser['username'];
                }
            } catch (Exception $e) {
                $logger->err(
                    sprintf('%s: buildMentions failed for user %s: %s', self::LOG_PREFIX, $userId, $e->getMessage())
                );
            }
        }
        return implode(' ', $mentions);
    }

    /**
     * @inheritDoc
     */
    public function buildMentionsFromUserIds(array $userIds, array $workspace = []): array
    {
        if (empty($userIds)) {
            return [];
        }
        $logger  = $this->services->get(SwarmLogger::SERVICE);
        $members = [];
        foreach ($userIds as $userId) {
            try {
                $mmUser = $this->resolveSwarmUser((string) $userId, $workspace);
                if ($mmUser !== null) {
                    $members[] = $mmUser['id'];
                } else {
                    $logger->warn(
                        sprintf('%s: no Mattermost account for user "%s"', self::LOG_PREFIX, $userId)
                    );
                }
            } catch (Exception $e) {
                $logger->warn(
                    sprintf('%s: lookup failed for user "%s": %s', self::LOG_PREFIX, $userId, $e->getMessage())
                );
            }
        }
        return array_values(array_unique($members));
    }
}
